# Site wide configuration

title: "FOSS4G 2017 - Boston, MA"
description: "Free and Open Source Software for Geospatial"
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
# url: "http://avidgeo.github.io/foss4g2017-dev"
feed:
  path: atom.xml

# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
highlighter: rouge

github: [metadata]
  kramdown:
    input: GFM
    hard_wrap: false
   toc_levels: 1..2
 gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

lsi: false
safe: true
source: foss4g2017-dev
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax


# Site owner
owner:
  name:
  email:
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
